apiVersion: v1
kind: Service

metadata:
  name: prometheus
  namespace: monitoring

  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'

spec:
  type: LoadBalancer

  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090

  selector:
    app: prometheus-server
