apiVersion: v1
kind: Service

metadata:
  name: grafana
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
  namespace: monitoring

spec:
  type: LoadBalancer

  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000

  selector:
    app: grafana
