apiVersion: v1
kind: Pod

metadata:
  name: kubia-liveness

spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: kubia

    livenessProbe:
      httpGet:
        path: /
        port: 8080

      initialDelaySeconds: 15
      periodSeconds: 5
      timeoutSeconds: 1

      successThreshold: 1
      failureThreshold: 3
